### PR TITLE
New Module: git_clone

### PR DESCRIPTION
**Pull request by domwhewell-sage**
This module will take discovered `CODE_REPOSITORY` events tagged with `git` and clone them onto the filesystem.

`FILESYSTEM` events are created which hold the path to the artifact and tags to indicate what artifact is (So in this case a `git` repository and it is a `folder`)

Other modules can then consume the `FILESYSTEM` event and perform some actions based on the tags.

The option `output_folder` is configurable as the `code_repos` folder has the potential to get quite large....

Todo:
- [x] Explore how to create a unit test for this module

### CODE REVIEW

**Comment by TheTechromancer** [comment]
Thinking about this, I can't wait for `excavate` to consume `FILESYSTEM` events. So many juicy things in there -- subdomains, emails. It's gonna be wild.

**Comment by domwhewell-sage** [comment]
Sorry for all the merging / Failing checks just trying to get the tests to pass 🤪

**Comment by TheTechromancer** [comment]
the struggle is real

**Comment by domwhewell-sage** [comment]
`test_module_leakix.py` why 😭

**Comment by TheTechromancer** [comment]
I think it's failing because of your `os.chdir()`.

**Comment by domwhewell-sage** [comment]
Thanks @TheTechromancer good spot!

**Review by TheTechromancer — APPROVED** [review]

**Comment by TheTechromancer** [comment]
Looks good to merge, but @liquidsec will have to approve since I made a few tweaks.

@domwhewell-sage if you plan on making a docker equivalent to this module, let me know and I can get you one of our internal tools we use to loot docker images.

**Comment by domwhewell-sage** [comment]
That's cool, I am planning on making a `docker_pull.py` module to download the layers from the docker repo into a tarball (Exploring the API instead of using the docker cli tool currently similar to https://github.com/sdenel/docker-pull-push)

**Review by liquidsec — APPROVED** [review]

**Pull request merged**
