### PR TITLE
Fix websocket connect

### PR DESCRIPTION
**Pull request by batgoose**
required for bbot-gui to connect

### CODE REVIEW

**Comment by TheTechromancer** [comment]
We need to either spin up a temporary websocket server during the tests, or patch it like were before (in `bbot_fixtures.py`):

image

**Comment by TheTechromancer** [comment]
@batgoose Please test the agent on the `async-testing` branch and let me know if you run into any issues. If not, we should be okay to close this.

**Comment by aconite33** [comment]
@batgoose to validate in testing frontend

**Comment by TheTechromancer** [comment]
confirmed async branch is working

**Pull request closed without merging**
