### PR TITLE
Fix syntax error in workflow file

### PR DESCRIPTION
**Pull request by domwhewell-sage**
This PR fixes a syntax error in the workflow file

### CODE REVIEW

**Comment by TheTechromancer** [comment]
Hey while you're at it can you add a check to make sure this workflow only runs on dev?

**Comment by domwhewell-sage** [comment]
Sure I have changed it to only checkout the dev branch and also changed the pull request branch name to not conflict with an existing branch name

**Comment by TheTechromancer** [comment]
Thanks, can you also add this at the top of the workflow like we've done for the autopublishing?

```yaml
    if: github.event_name == 'push' && (github.ref == 'refs/heads/dev')
```

**Comment by domwhewell-sage** [comment]
The workflow currently runs at midnight each day instead of on push events. So I'm not sure that if statement is required

Edit: The successful run should open these 2 Pull requests
image

**Review by TheTechromancer — APPROVED** [review]

**Comment by TheTechromancer** [comment]
Got it. I wasn't sure if having it in multiple branches would trigger multiple times, but I think you're right, it shouldn't be needed. Approved.

**Pull request merged**
