### PR TITLE
bump baddns, lower dnswalk timeout settings

### PR DESCRIPTION
**Pull request by liquidsec**
Upgrading to baddns 1.1.815, and significantly lowering settings regarding the NS module's DNSWalk(). This should significantly speed baddns up in situations where one or more nameservers aren't responding.

### CODE REVIEW

**Comment by TheTechromancer** [comment]
Looks good, but can we change it to respect BBOT's DNS settings? The default is 1 retry, 5 second timeout.

**Comment by liquidsec** [comment]
It does respect them. The settings for DNS walk are different than all of the other DNS operations. For everything else, it's already using bbot settings via the bbot dns client

**Comment by liquidsec** [comment]
if you mean just matching them up with that im fine with that, what i picked was fairly arbitrary

**Comment by liquidsec** [comment]
https://github.com/blacklanternsecurity/bbot/pull/1718/commits/26a60decbaf726021a545626bb00e4fd62d2dc1f

**Comment by TheTechromancer** [comment]
I mean we should pass through the BBOT settings into baddns.

**Comment by liquidsec** [comment]
Thats already happening. Just not with the DNS walk function specifically (this was intentional)

**Comment by liquidsec** [comment]
I suppose we can pass them in manually, but the consequences of setting the timeout too low in this case is worse than normal, because it can trigger weird false positives.

**Review by TheTechromancer — APPROVED** [review]

**Pull request merged**
