### PR TITLE
Updated download count badge

### PR DESCRIPTION
**Pull request by ooooo-create**
try to updated download count badge
- [x] xref [Updated download count badge  #1087 ](https://github.com/blacklanternsecurity/bbot/issues/1087)

### CODE REVIEW

**Comment by TheTechromancer** [comment]
Thanks for taking this on. But this badge has a hardcoded number. We need it to update automatically, e.g.:

```markdown
![PyPi Downloads](https://static.pepy.tech/personalized-badge/bbot?right_color=orange)
```

My hope was to use "Pepy", but I wanted the badge's colors to match the others.

**Comment by ooooo-create** [comment]
> Thanks for taking this on. But this badge has a hardcoded number. We need it to update automatically, e.g.:
> 
> ```
> PyPi Downloads
> ```
> 
> My hope was to use "Pepy", but I wanted the badge's colors to match the others.

Got it, Thanks!
For match the others, i also add the `left_color=grey`.
And I still have a confusion,we also have some green badge,should we unify the colors?

**Comment by TheTechromancer** [comment]
> we also have some green badge,should we unify the colors?

Let's just separate them so the orange and green are grouped together.

**Comment by ooooo-create** [comment]
> > we also have some green badge,should we unify the colors?
> 
> Let's just separate them so the orange and green are grouped together.

Thanks!
i separated different colors, like this
image

**Comment by TheTechromancer** [comment]
Perfect! Thanks @ooooo-create and congrats on your first contribution! 🎉

**Review by TheTechromancer — APPROVED** [review]

**Pull request merged**
