### PR TITLE
GEOIP Integration

### PR DESCRIPTION
**Pull request by tycoonslive**
Integration of a module for location information :
country, region, city, zip, code, latitude, longitude with the ipstcack.com api

### CODE REVIEW

**Comment by TheTechromancer** [comment]
Thanks for the PR! To get the lint tests to pass, you need to do:
```bash
poetry run black .
```
This auto-formats the code with correct indents, line lengths, etc.

**Comment by tycoonslive** [comment]
Ok, I try tonight or tomorrow
# --recurse-submodules will also clone the BBOT Module Playground into bbot/modules/playground
git clone --recurse-submodules git@github.com:tycoonslive/bbot.git && cd bbot

# install poetry
curl -sSL https://install.python-poetry.org | python3 -
poetry install
poetry shell

bbot --help
I followed the wiki, but I have a bug when I run poetry and I don't know this truck U+1F61E at all
` →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
`

**Comment by TheTechromancer** [comment]
What version of poetry do you have?

**Comment by tycoonslive** [comment]
> Quelle version de la poésie avez-vous?
Poetry version 1.1.14

**Comment by TheTechromancer** [comment]
Can you try:
```bash
curl -sSL https://install.python-poetry.org | python3 - --uninstall
curl -sSL https://install.python-poetry.org | python3 - --preview
```

**Comment by tycoonslive** [comment]
Well, after a lot of tries, I find myself this time with a PEP400 version error. I think the easiest way is to integrate it into your dev environment so you can use it on your project. For my part, I don't find it very simple even if I love your project

**Comment by TheTechromancer** [comment]
I'd still like to help if possible. Were you able to upgrade poetry to the latest version? If so, setting up a dev environment really should be as easy as cloning a fresh project and doing `poetry install`.

**Comment by tycoonslive** [comment]
yes Poetry (version 1.2.2)
I spent a lot of time debugging this, I'm frustrated that it doesn't work :)
the new error 
Invalid PEP 440 version: '2.3.0-nmu1-b1'
But I don't have a candidate version on my system for this
I'm sorry I can't do more. I know that project development is very time consuming and help is always welcome 
I appreciate your support, very good mentality

**Comment by TheTechromancer** [comment]
Okay I understand. Thanks for your effort. If you ever feel inclined to give it another try, I'd be happy to help.

**Review by liquidsec — APPROVED** [review]

**Pull request merged**
